apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "saferwall.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "64M"
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    {{- if index .Values "cert-manager" "enabled" }}
    cert-manager.io/cluster-issuer: {{ index .Values "cert-manager" "ingressShim" "defaultIssuerName" }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.global.frontendDomainName }}
    - {{ .Values.global.backendDomainName }}
    {{- if .Values.website.enabled }}
    - {{ .Values.global.websiteDomainName }}
    {{- end }}
    secretName: {{ include "saferwall.fullname" . }}-tls
  rules:
  - host: {{ .Values.global.frontendDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.fullname" . }}-frontend
          servicePort: {{ .Values.frontend.service.port }}
  - host: {{ .Values.global.backendDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.fullname" . }}-backend
          servicePort: {{ .Values.backend.service.port }}
{{- if .Values.website.enabled }}
  - host: {{ .Values.global.websiteDomainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "saferwall.fullname" . }}-website
          servicePort: {{ .Values.website.service.port }}
{{- end }}

