[backend]
address = "http://localhost:8081"
admin_user = "<admin>"
admin_pwd = "<password>"

[consumer]
# Possible values "panic", "fatal", "error", "warn", "info", "debug", "trace"
log_level = "warn"

[ml]
address = 'http://localhost:8000'

[nsq]
lookupd = ["localhost:4161",]

[minio]
endpoint = "localhost:9000"
seckey = "<seckey>"
accesskey = "<accesskey>"
spacename = "samples"
ssl = false

[multiav]
  [multiav.avast]
  enabled = false
  addr = "avast-svc:50051"

  [multiav.avira]
  enabled = true
  addr = "avira-svc:50051"

  [multiav.bitdefender]
  enabled = false
  addr = "bitdefender-svc:50051"

  [multiav.clamav]
  enabled = true
  addr = "clamav-svc:50051"

  [multiav.comodo]
  enabled = true
  addr = "comodo-svc:50051"

  [multiav.drweb]
  enabled = false
  addr = "drweb-svc:50051"

  [multiav.eset]
  enabled = false
  addr = "eset-svc:50051"

  [multiav.fsecure]
  enabled = false
  addr = "fsecure-svc:50051"

  [multiav.kaspersky]
  enabled = false
  addr = "kaspersky-svc:50051"

  [multiav.symantec]
  enabled = false
  addr = "symantec-svc:50051"

  [multiav.sophos]
  enabled = false
  addr = "sophos-svc:50051"

  [multiav.mcafee]
  enabled = false
  addr = "mcafee-svc:50051"

  [multiav.windefender]
  enabled = true
  addr = "windefender-svc:50051"
