name: Generate Vagrant Box

on:
  pull_request:
    branches: [master]

jobs:
  build-vagrant-box:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup config
        run: cp example.env .env

      - name: Install Vagrant
        run: make vagrant-install

      - name: Install VirtualBox
        run: make vbox-install

      - name: Create Vagrant box
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libarchive-tools
          cd build/vagrant
          vagrant up

      - name: Create box package
        run: make vagrant-package

      - name: Authenticate to Vagrant cloud
        run: make vagrant-login

      - name: Publish the box
        run: make vagrant-login
